### PR TITLE
Android Upgrade+Bug Fixes+Cellular Compatability

### PR DESCRIPTION
**Pull request by irinil**

### CODE REVIEW

**Comment by irinil** [comment]
Maybe we accessed it the same time?

**Comment by sastry17** [comment]
WiFi SSID is not shown on the home screen


MicrosoftTeams-image

**Comment by irinil** [comment]
This is issue doesn't exist with the current pull request. So, I don't know what it may cause it. Do you want me to check it for this pull request?

105573759_197074144951310_7483006716343263606_n

**Comment by sastry17** [comment]
can you please commit all your changes to the GSoC2020 branch directly? i think there are some conflicts.

**Comment by irinil** [comment]
Do you mean without a pull request right?

**Comment by sastry17** [comment]
Yes, commit the changes to the GSoC2020 branch.

**Comment by sastry17** [comment]
The SSID is shown after specifying permissions and restarting the wifi and the app.

**Pull request closed without merging**
